[phases.setup]
nixPkgs = ["nodejs_24", "pnpm"]

[phases.install]
cmds = [
  "rm -f pnpm-lock.yaml",
  "pnpm install --no-frozen-lockfile --ignore-scripts"
]

[phases.build]
cmds = ["pnpm --filter @workspace/admin-panel run build"]

[start]
cmd = "pnpm --filter @workspace/admin-panel run start"
